# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - dev
      - 'feature/**'
      - 'feat/**'
      - 'bugfix/**'
      - 'fix/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - name: Commit lint
        uses: ahmadnassri/action-commit-lint@v2
        with:
          config: ./commitlint.config.ts
      - name: Code lint
        if: always()
        run: pnpm lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - name: Build
        run: pnpm build
