# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - dev
      - 'feature/**'
      - 'feat/**'
      - 'bugfix/**'
      - 'fix/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit linter
        uses: wagoid/commitlint-github-action@v2.0.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Linter
        run: npm run lint
      - name: Build
        run: npm run build
